### ISSUE TITLE
Release v 1.1.0 is not backward compatible

### ISSUE THREAD

**Issue by jcass77** [mopidy/mopidy-alsamixer#10]
The changes introduced by PR #9 do not appear to be backward compatible with Raspbian Wheezy installations still running Mopidy 1.0 and gstreamer-0.10 (i.e. everyone running MusicBox 0.6):

```
2017-02-14 07:55:54,066 - INFO     Loading config from command line options
2017-02-14 07:55:58,216 - INFO     Enabled extensions: moped, stream, spotify_tunigo, gmusic, softwaremixer, file, musicbox_webclient, websettings, tunein, mopify, podcast-itunes, internetarchive, local, alarmclock, mpd, http, local-images, dirble, podcast, alsamixer, mobile, m3u, youtube, simple-webclient, pandora, local-sqlite
2017-02-14 07:55:58,220 - INFO     Disabled extensions: spotify, scrobbler, subsonic, somafm, audioaddict, soundcloud
2017-02-14 07:55:59,224 - ERROR    Extension alsamixer failed during setup, this might have left the registry in a bad state.
Traceback (most recent call last):
  File "/var/lib/git/mopidy/mopidy/__main__.py", line 145, in main
    extension.setup(registry)
  File "/usr/local/lib/python2.7/dist-packages/mopidy_alsamixer/__init__.py", line 32, in setup
    from mopidy_alsamixer.mixer import AlsaMixer
  File "/usr/local/lib/python2.7/dist-packages/mopidy_alsamixer/mixer.py", line 10, in <module>
    from gi.repository import GstAudio
  File "/usr/lib/python2.7/dist-packages/gi/__init__.py", line 27, in <module>
    from ._gi import _API, Repository
ImportError: could not import gobject (error was: ImportError('When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject".',))
2017-02-14 07:55:59,327 - INFO     Setup Mopify
2017-02-14 07:56:08,901 - ERROR    Did not find unique mixer "alsamixer". Alternatives are: software, none
2017-02-14 07:57:49,127 - INFO     Starting Mopidy 1.1.2
2017-02-14 07:57:53,868 - INFO     Loading config from builtin defaults
2017-02-14 07:57:54,087 - INFO     Loading config from /home/mopidy/.config/mopidy/mopidy.conf
2017-02-14 07:57:54,187 - INFO     Loading config from command line options
```

A brief search seemed to indicate that this has something to do with trying to use static gst bindings combined with dynamic PyObject bindings at the same time: https://pygobject.readthedocs.io/en/latest/porting.html.

We probably can't keep on ensuring backwards compatibility for MusicBox 0.6 users - I'm posting the error log here for reference purposes in case others run into the same issue.

**Comment by jodal** [comment]
Ah, then this should have been 2.0. I'll bump the dependency on Mopidy at least.

**Comment by adamcik** [comment]
Whoops, I should have caught that during review.

It should also have a require for the gst version around https://github.com/mopidy/mopidy-alsamixer/blob/master/mopidy_alsamixer/mixer.py#L10

Other alternative is just to implement these functions our self like the PR started with.
